[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "python-telegram-bot==20.8",
    "requests>=2.32.3",
    "telegram>=0.0.1",
    "yt-dlp>=2025.5.22",
    "pyrogram>=2.0.106",
    "tgcrypto>=1.2.5",
]
